### ISSUE TITLE
Name/Branding for project?

### ISSUE THREAD

**Issue by frankdugan3** [frankdugan3/pyro#6]
I'm not super happy with `Phlegethon` as the project name (although it is growing on my). I'm open to any suggestions on better branding, as well as a logo (I have 0 design skill).

**Comment by BryanJBryce** [comment]
I agree with a rename. I have no idea what Phlegethon is or how to pronounce it or spell it without looking.

My suggestion would be Maple UI. Ash wood is prized for being a utility wood, one used to make tool handles and the like. Since this library's goal is to put a veneer on Ash backends it could be named for a wood prized for its beauty. Maple UI is unused as a project name on hex or anywhere else. It could quickly become googlable like Ash Framework is. Also, it's easy to remember and spell and pronounce.

**Comment by frankdugan3** [comment]
Ooh, I like that! That is definitely going to the top of the list of options.

**Comment by zachdaniel** [comment]
I like Maple UI :D

**Comment by frankdugan3** [comment]
I'm now considering `PyroUI` and `CinderBox`. Thoughts?

**Comment by zachdaniel** [comment]
PyroUI is excellent :) not so much a fan of CinderBox

**Comment by Nefcairon** [comment]
I quite dislike Maple, I'm fine with Pyro.

I am not an English native, so does this make sense? When you burn something with explosions (that's pyro, isn't it?), all that's left is ash.

**Comment by frankdugan3** [comment]
The deed is done! :rocket:
